### ISSUE TITLE
Client side integration not setup

### ISSUE THREAD

**Issue by kitajchuk** [NodeSquarespace/node-squarespace-jsont#13]

**Comment by foleyatwork** [comment]
I've got JSONT and Predicates up and running here. I'm still trying to figure out how I'm going to deal with the slug, moment, and phpjs dependencies in formatters.

https://github.com/foleyatwork/node-squarespace-jsont

**Comment by kitajchuk** [comment]
Hmm, perhaps we can port some Javascript from Squarespace for those and just include it. Ideally those methods would be using the same code anyway so the results are identical in each scenario. Right now it feels kind of choppy.

**Comment by foleyatwork** [comment]
Unfortunately our formatters are written in Java, but I'll see what I can do to remove those dependencies and port them over to JavaScript.

**Comment by kitajchuk** [comment]
I'm starting to smell a good project. It would be rad if Squarespace could open source their JSONT implementation so legitimate ports could be made for other languages.

**Comment by foleyatwork** [comment]
On my to-do list : )

**Comment by kitajchuk** [comment]
Sweet! This is looking good so far for the client implementation :)

**Comment by foleyatwork** [comment]
I have everything done except for date formatting. You don't happen to know of anything that does YUI date formatting without the YUI dependencies, do you? (haha)

**Comment by kitajchuk** [comment]
Well, the reason I used the phpjs strftime is because it is the same formatting style that YUI uses, they even state it here, http://yuilibrary.com/yui/docs/api/classes/Date.html#method_format.

The actual code for it is here, maybe a bit loftier than we would want for a static implementation just for one formatter, but using just this function is always an option for now as well:
https://github.com/kvz/phpjs/blob/master/functions/datetime/strftime.js

**Comment by foleyatwork** [comment]
Beautiful! I think it's probably fine to jack that function and provide attribution in the source for now.

**Comment by foleyatwork** [comment]
Okay, got it to work. I need to test to make sure I didn't break anything in the node implementation but if all goes well a pull request will be coming by the end of the day today.

**Comment by foleyatwork** [comment]
Bad news... I couldn't get the phpjs stuff to parse in both the browser and node. So I guess I'm either going to write my own date format function or find another that works. More updates another time.

**Comment by kitajchuk** [comment]
This looks like it could be promising... https://github.com/samsonjs/strftime.
