### ISSUE TITLE
Using colons or other characters in {.equal?} renders in Squarespace, but not node-squarespace-server.

### ISSUE THREAD

**Issue by ghost** [NodeSquarespace/node-squarespace-jsont#30]
Using multiple word arguments in Squarespace doesn't work by default, but you can get it to work in Squarespace's JSON-T by placing `:` or `#` to fill the empty spaces. This doesn't render in the node-squarespace-server causing template issues and crashes with "too many {end} statement" errors.
## Squarespace JSON-T Hack {.equal?} hack:

```
{.equal?:categoryFilter:"Category Name"}
   <!-- More -->
{.end}
```

**Comment by chrisschaub** [comment]
Yes, same problem. Works on squarespace, but not node-squarespace-server. Any chance for a fix?

**Comment by thomkrillis** [comment]
+1

Having this issue atm.

**Comment by aenhsaihan** [comment]
Please merge PR for this error.
